# Promise

## What is `promise`?

-   Promise is a built-in Javascript object for asynchronous
-   비동기를 도와주는 객체이다.
-   정해진 장시간의 기능을 수행하고 나서,

    -   정상적으로 작동했다면 **성공의 메세지 + 결과값**을 전달해주고,
    -   기능을 수행하다가 예상치 못한 결과가 나왔을 때 **error**를 전달한다.

## state, producer, consumer

1. state
    - pending: 기능 수행중인 상태
    - fulfilled: 성공
    - rejected: 실패
2. producer / consumer
    - producer: promise 오브젝트
    - consumer: 우리의 데이터를 소비

## code

**1. Producer 정의**

```js
const promise = new Promise((resolve, reject) => {
    //doing some heavy work(network, read files)
    console.log('...');
    setTimeout(() => {
        resolve('junha');
    }, 2000);
    reject(new Error('no network'));
});
```

-   When new Promise is created, the executor runs automatically!

**2. Consumer 정의: then, catch, finally**

```js
promise
    .then((value) => {
        console.log(value);
    })
    .catch((error) => {
        console.log(error);
    })
    .finally(() => {
        console.log('finally');
    });
```

-   **프로미스 체이닝**: then은 promise를 리턴하기 때문에 catch로 받아올 수 있다.
    -   resolve(parameter) => then(value)
    -   reject(error) => catch(error)
    -   finally:성공의 유무에 상관없이 호출된다.

**3. Promise Chaining**

```js
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
});

fetchNumber
    .then((num) => num * 2)
    .then((num) => num * 3)
    .then((num) => {
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(num - 1), 1000);
        });
    });
    .then(num => console.log(num))
```

-   then이 promise객체를 반환하기 때문에 체이닝이 가능하다.

**4. Error Handling**

```js
const getHen = () => {
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('🐔'), 1000);
    });
};

const getEgg = (hen) =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${hen} => '🥚'`), 1000);
    });

const getFry = (egg) =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => '🥯'`), 1000);
    });

getHen()
    .then((hen) => getEgg(hen))
    .catch((error) => {
        return `${egg} => '🍕'`;
    })
    .then((egg) => getFry(egg))
    .then((meal) => console.log(meal));
```

```js
.then((hen) => getEgg(hen))
.then(getEgg)
```

-   아규먼트가 동일할 경우 생략이 가능하다.
